version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: "link_minify_webapp"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=link_minify
      - DB_USERNAME=link_minify_user
      - DB_PASSWORD=password
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=link_minify_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=link_minify
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
